services:
  web:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    restart: always